set(_CATKIN_CURRENT_PACKAGE "urdf_tut")
set(urdf_tut_VERSION "0.0.0")
set(urdf_tut_MAINTAINER "shashank <shashank@todo.todo>")
set(urdf_tut_PACKAGE_FORMAT "2")
set(urdf_tut_BUILD_DEPENDS )
set(urdf_tut_BUILD_EXPORT_DEPENDS )
set(urdf_tut_BUILDTOOL_DEPENDS "catkin")
set(urdf_tut_BUILDTOOL_EXPORT_DEPENDS )
set(urdf_tut_EXEC_DEPENDS )
set(urdf_tut_RUN_DEPENDS )
set(urdf_tut_TEST_DEPENDS )
set(urdf_tut_DOC_DEPENDS )
set(urdf_tut_URL_WEBSITE "")
set(urdf_tut_URL_BUGTRACKER "")
set(urdf_tut_URL_REPOSITORY "")
set(urdf_tut_DEPRECATED "")